SELECT * FROM Customer;

-- 1.What is the total revenue generated by male and female customers?

SELECT gender, SUM("purchase_amount_(usd)") AS total_revenue
FROM Customer
GROUP BY gender;

-- 2.Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, "purchase_amount_(usd)"
FROM Customer
WHERE discount_applied='Yes' AND "purchase_amount_(usd)" >= (SELECT AVG("purchase_amount_(usd)") FROM Customer);

-- 3.Which are the top 5 products with the highest average review ratings?

SELECT item_purchased, ROUND(AVG(review_rating)::numeric,2) AS avg_rating
FROM Customer 
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- 4.Compare the average purchase amounts between Standard and Express shipping methods.

SELECT shipping_type, ROUND(AVG("purchase_amount_(usd)"),2) AS avg_purchase_amount
FROM Customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- 5.Do subscribed customers spend more? 
--   Compare the average spending and total revenue of subscribed and non-subscribed customers.

SELECT subscription_status, COUNT(customer_id) AS total_customer,
ROUND(AVG("purchase_amount_(usd)"),2) AS avg_spending, 
SUM("purchase_amount_(usd)") AS total_revenue
FROM Customer
GROUP BY subscription_status
ORDER BY total_revenue;

-- 6.Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM Customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- 7.Segment customers into New, Returning, and Loyal categories based on their total number of 
--   previous purchases, and show the number of customers in each segment.

WITH CTE AS
(SELECT 	customer_id, previous_purchases,
 CASE 
     WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END AS customers_segment
 FROM Customer)

SELECT customers_segment, COUNT(*) as no_of_customer
FROM CTE
GROUP BY customers_segment;

-- 8.What are the top 3 most purchased products within each category?

WITH CTE AS (
SELECT category, item_purchased, 
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM Customer
GROUP BY category, item_purchased)

SELECT item_rank, category, item_purchased, total_orders
FROM CTE
WHERE item_rank<=3;

-- 9.Are repeat buyers (customers with more than 5 previous purchases) more likely to subscribe?

SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases >5
GROUP BY subscription_status;

-- 10.What is the revenue contribution of each age group?

 SELECT age_group, SUM("purchase_amount_(usd)") AS total_revenue_contribution
 FROM Customer 
 GROUP BY age_group
 ORDER BY total_revenue_contribution DESC;


